### ISSUE TITLE
Make parse_time/parse_datetime part of public API again

### ISSUE THREAD

**Issue by TimoFreiberg** [badboy/iso8601#26]
When using iso8601 to parse dates in addition to more input, it is quite annoying that the leftover input is thrown away [here](https://github.com/badboy/iso8601/blob/f412dc24c7b48ecdc0799cb246ba1895c4bad25c/src/lib.rs#L183).
It doesn't have to return the nom `IResult`, but would you mind if the library offers variants of `iso8601::{date,time,datetime}` that return a `(leftover_input, result)` tuple in the `Ok` case?

**Comment by magnusuMET** [comment]
It would be great to have access to the `nom` based parser of this crate to compose a `nom` parser elsewhere

**Comment by JonasOlson** [comment]
Yes, this would be great, and precisely in the spirit of parsing combinators and unlocking the powers of nom! Dates and times in particular are natural as part of something larger, such as a log file, or an email, that one might want to parse.

Is turning `mod parsers` back into `pub mod parsers` on [this line](https://github.com/badboy/iso8601/blob/612a2a6756d65e50e9e061ac004abb31d04b0468/src/lib.rs#L41) all it would take?
