### ISSUE TITLE
impl Display for Duration

### ISSUE THREAD

**Issue by tobz1000** [badboy/iso8601#31]
Similar to the implementations for `Date`, `Time`, `DateTime`.

**Comment by hoodie** [comment]
like that #39 ?

**Comment by meh** [comment]
Yes, but even better if it didn't include the parts when they're 0 :panda_face:

**Comment by hoodie** [comment]
wait, is everything optional?
is `"P"` a valid duration?

**Comment by meh** [comment]
>Date and time elements including their designator may be omitted if their value is zero, and lower-order elements may also be omitted for reduced precision. For example, "P23DT23H" and "P4Y" are both acceptable duration representations. However, at least one element must be present, thus "P" is not a valid representation for a duration of 0 seconds. "PT0S" or "P0D", however, are both valid and represent the same duration.

**Comment by hoodie** [comment]
what should be the default in case of this?
```rust
Duration::YMDHMS {
    year: 0,
    month: 0,
    day: 0,
    hour: 0,
    minute: 0,
    second: 0,
    millisecond: 0
}
```

**Comment by meh** [comment]
I'd just use `P0D`.

**Comment by hoodie** [comment]
ok, I think this should do the trick
https://github.com/badboy/iso8601/pull/39/files#diff-ec89651dd36e9112dfcea9afbf96be3d5811835b15f742da884d9ab1131aeafaR329

should be done now @meh @badboy

**Comment by meh** [comment]
Looks good to me, but who am I to say :panda_face:
